ACCEPT FRASE PROMPT 'ESCRIBE UNA FRASE ';
DECLARE
	CADENA VARCHAR2(100):='&FRASE';
BEGIN
		
	FOR I IN REVERSE 1..LENGTH(CADENA) LOOP
	
	DBMS_OUTPUT.PUT(SUBSTR(CADENA,I,1));	

	END LOOP;
DBMS_OUTPUT.NEW_LINE;
	
END;
/